### ISSUE TITLE
environment mmdetection3d

### ISSUE THREAD

**Issue by CatOneTwo** [AIR-THU/DAIR-V2X#11]
Hi, thanks for your excellent work!
I want to know how to control mmdetection3D==0.17.1,  the tutorial on mmdetection3d didn't mention that.

**Comment by yuhb94** [comment]
Thanks for your attention. our mmdetection3d related packages are: mmcv-full==1.3.14, mmdet=2.14.0, mmpycocotools==12.0.3, mmsegmentation==0.14.1.
