### ISSUE TITLE
Error occured when reimplementing pointpillar on vic3d dataset

### ISSUE THREAD

**Issue by CatOneTwo** [AIR-THU/DAIR-V2X#12]
Hi, I  have followed the **configs/vic3d/late-fusion-pointcloud/pointpillars/README.md** to prepare the dataset, but when I try to train PointPillar model with trainval_config_i.py, the error occurred as
 `No such file or directory: '../../../../data/DAIR-V2X/cooperative-vehicle-infrastructure/infrastructure-side//kitti_infos_train.pkl`.

I have checked the converted dataset, which indeed doesn't contain `kitti_infos_train.pkl`. So how can I generate this file, thank you!

**Comment by yuhb94** [comment]
You should convert the dataset format as MMDetection3D requiring. More details refer to https://mmdetection3d.readthedocs.io/en/latest/data_preparation.html.

**Comment by deyang2000** [comment]
> Hi, I have followed the **configs/vic3d/late-fusion-pointcloud/pointpillars/README.md** to prepare the dataset, but when I try to train PointPillar model with trainval_config_i.py, the error occurred as `No such file or directory: '../../../../data/DAIR-V2X/cooperative-vehicle-infrastructure/infrastructure-side//kitti_infos_train.pkl`.
> 
> I have checked the converted dataset, which indeed doesn't contain `kitti_infos_train.pkl`. So how can I generate this file, thank you!
![bc31d22f2f9ffa1c2ba3e06fa13ce6f](https://github.com/AIR-THU/DAIR-V2X/assets/129513825/a50a4aed-2661-4127-ba87-c712af2753c7)

I had the same problem. Did you solve it? I saw the corresponding download link in the mmdet3d manual, but I don't think it's right.

**Comment by deyang2000** [comment]
I had some possible solutions but didn't implement them because I switched to using the V2X-set data set for now. The general idea is to follow the documentation for custom datasets in mmdet3d.

**Comment by Ericchen328** [comment]
请问有什么解决方案吗
