### ISSUE TITLE
The question about the end of the road camera FOV

### ISSUE THREAD

**Issue by zxzzz525** [AIR-THU/DAIR-V2X#17]
Hello, what is the focal length of the lens used for the infrastructure-side camera, so that I can calculate the FOV of theinfrastructure-side camera?

**Comment by haibao-yu** [comment]
> Hello, what is the focal length of the lens used for the infrastructure-side camera, so that I can calculate the FOV of theinfrastructure-side camera?

Hi, you can calculate the FOV with the camera intrinsic parameters.
