### ISSUE TITLE
Some infrastructure pcd file missing in the cooperative label_world

### ISSUE THREAD

**Issue by smallscientist1** [AIR-THU/DAIR-V2X#18]
When using this dataset, I found that in ./cooperative-vehicle-infrastructure/cooperative/data_info.json file, the pcd file in "infrastructure_pointcloud_path" attribute  sometimes doesn't exist at all. Is this a problem of the dataset?

**Comment by haibao-yu** [comment]
> When using this dataset, I found that in ./cooperative-vehicle-infrastructure/cooperative/data_info.json file, the pcd file in "infrastructure_pointcloud_path" attribute sometimes doesn't exist at all. Is this a problem of the dataset?

Can you provide more details? For example, which idx of the infrastructure_pointcloud_path.

**Comment by haibao-yu** [comment]
This is normal. We associate vehicle-side and infrastructure-side frames according to a certain time difference constraint. There are some vehicle-side frames at the edge of the clip without corresponding infrastructure-side frames
