### ISSUE TITLE
Segmentation fault when test "single-infrastructure-side".

### ISSUE THREAD

**Issue by JiayinDeng** [AIR-THU/DAIR-V2X#21]
This problem may be caused by the empty test dataset of the `single-infrastructure-side`. Where can I get the test data and reproduce the results described in the paper?

**Comment by haibao-yu** [comment]
> This problem may be caused by the empty test dataset of the `single-infrastructure-side`. Where can I get the test data and reproduce the results described in the paper?

The experiment results reported in paper is evaluated with val part. And we are running a VIC3D challenge. The test data will be released with the challenge. More information about the challenge could be seen in https://mp.weixin.qq.com/s/O1YpJ4ARfI1tyd7buY-mdg.
