### ISSUE TITLE
empty obj when browse dataset in mmdet3d framework

### ISSUE THREAD

**Issue by Italian-PAO** [AIR-THU/DAIR-V2X#24]
Hi, thanks a lot for your great contribution in V2X area! 
When I follow your [instruction ](https://github.com/AIR-THU/DAIR-V2X/blob/main/configs/vic3d/late-fusion-pointcloud/pointpillars/README.md)of late fusion, some problems occured.
I download the dataset from the official website, and convert the data using dair2kitti.py, when I evaluate the pretrained checkpoints you provided, the mAP result is correct.
Then I want to train the model in mmdet3d, so I create data using the command as followed
`python tools/create_data.py kitti --root-path ~/code/DAIR-V2X-main/data/DAIR-V2X/cooperative-vehicle-infrastructure/vehicle-side/ --out-dir ~/code/DAIR-V2X-main/data/DAIR-V2X/cooperative-vehicle-infrastructure/vehicle-side/`
and the following files are generated successfully
![image](https://user-images.githubusercontent.com/49139695/204077798-daee7165-e460-4cec-b681-be1eaf72b85d.png)
However, when I browse the dataset using command:
`python tools/misc/browse_dataset.py configs/pointpillars/trainval_config_v.py --output-dir tools/misc/veh_side/ --task det`
the output xxx_points.obj files are empty when visualize them like this:
![image](https://user-images.githubusercontent.com/49139695/204078261-7a838b39-46b2-427a-b5ef-90c060ceb77b.png)
but there is data like this when I read the files as text
![image](https://user-images.githubusercontent.com/49139695/204078101-18c7543c-80db-494a-9246-adfe59c5a7c8.png)
and the xxx_gt.obj files are like this:
![image](https://user-images.githubusercontent.com/49139695/204078240-e150c61c-d9f5-462a-adb3-940f9c94f731.png)
What could be the reason for this problem? I will appreciate it a lot if you could share your advice, thank you!

**Comment by DurbinLiu** [comment]
Hi, have you found the exact reason for this ?
