### ISSUE TITLE
The velocities in TCLF framework

### ISSUE THREAD

**Issue by colian** [AIR-THU/DAIR-V2X#31]
Hi, according to the readme file in "configs/vic3d/late-fusion-pointcloud/pointpillars/", the perfromance is directly evaluated after obtaining two model trained by infrastructure-side and vehicle-side respectively. 
So, when does the "MLP to predict their velocities" in Figure 3 been trained?

Looking forward to your reply. Thank you.

**Comment by haibao-yu** [comment]
> Hi, according to the readme file in "configs/vic3d/late-fusion-pointcloud/pointpillars/", the perfromance is directly evaluated after obtaining two model trained by infrastructure-side and vehicle-side respectively. So, when does the "MLP to predict their velocities" in Figure 3 been trained?
> 
> Looking forward to your reply. Thank you.

The velocity computation is very simple, "For matched vehicles, we compute their velocities directly. For unmatched vehicles, we feed the position and motion information of the current scene into an MLP to predict their velocities."
For MLP prediction, please refer to the operations in file "./v2x/models/model_utils/late_fusion_utils.py":
```
 model = LinearRegression()
 model.fit(x, y)
 offset = model.predict(frame2.center[:, :2]) * delta2 / delta1
```
