### ISSUE TITLE
For vis_label_in_image.py

### ISSUE THREAD

**Issue by Drafaa** [AIR-THU/DAIR-V2X#33]
There are some problem in vis V2X-V(tools/visualize/vis_label_in_image.py line 25), in this dataset, you should use 
`label_path = osp.join(path, data_info["label_camera_std_path"])`
to replace 
`label_path = osp.join(path, data_info["label_lidar_std_path"])`
to get right image!
@haibao-yu

**Comment by haibao-yu** [comment]
> There are some problem in vis V2X-V(tools/visualize/vis_label_in_image.py line 25), in this dataset, you should use `label_path = osp.join(path, data_info["label_camera_std_path"])` to replace `label_path = osp.join(path, data_info["label_lidar_std_path"])` to get right image! @haibao-yu

Very thanks for your feedback. We have solved this issue in https://github.com/AIR-THU/DAIR-V2X/commit/0e8ae620937a0bf59bb2e85549441e0a5b2d1bb5.
