### ISSUE TITLE
Mis-alignment in the validation set on batch 54, 55

### ISSUE THREAD

**Issue by ju40268** [AIR-THU/DAIR-V2X#36]
Hi - 

We found that within for the validation dataset -  
Based on the mapping information `cooperative-vehicle-infrastructure/cooperative/data_info.json`
Vehicle side only has `batch_id` 55 and 54. However on the Infra side only has batch_id 54. 
I would appreciate some clarification on the missing label set 55 if that make sense.

Thanks!

**Comment by haibao-yu** [comment]
> Hi -
> 
> We found that within for the validation dataset - Based on the mapping information `cooperative-vehicle-infrastructure/cooperative/data_info.json` Vehicle side only has `batch_id` 55 and 54. However on the Infra side only has batch_id 54. I would appreciate some clarification on the missing label set 55 if that make sense.
> 
> Thanks!

Thanks for your feedback. This case is normal because we dropped some inappropriate infrastructure segments in associating two-side frames. We have reorganized the dataset and will release a new version recently.
