### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by fanhaiting** [AIR-THU/DAIR-V2X#37]
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`

**Comment by haibao-yu** [comment]
> RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`

There are no more detailed information. And we will close this issue.
