### ISSUE TITLE
Exact version of environment configuratioin

### ISSUE THREAD

**Issue by shb9793** [AIR-THU/DAIR-V2X#5]
Thanks for your great work!

Besides mmdet3d==0.17.1, I would like to know the exact environment configuration information, including the versions of cuda, pytorch, mmcv, mmdetection and mmseg. I want to reproduce your experimental results more accurately.

**Comment by yuhb94** [comment]
Thanks for your attention. cuda==11.1, torch==1.9.0, mmcv-full==1.3.14, mmdet=2.14.0, mmpycocotools==12.0.3, mmsegmentation==0.14.1. Looking forward to your reproduced results.

**Comment by shb9793** [comment]
Thanks for your reply! I will try my best based on your great contributions.
