### ISSUE TITLE
When i run the bash scripts/eval_lidar_late_fusion_pointpillars.sh, the reported error is that KeyError: 'GroupFree3DMHA is already registered in attention'

### ISSUE THREAD

**Issue by WangzcBruce** [AIR-THU/DAIR-V2X#58]
![image](https://github.com/AIR-THU/DAIR-V2X/assets/45158420/a7285f8e-5371-4d60-a469-5cd47db80eb7)

**Comment by luqinwei** [comment]
I have the same problem. How did you solve it？

**Comment by Uchan1996** [comment]
I also have the same issue.
Anyone solved this issue?
