### ISSUE TITLE
请问有视频数据集吗？

### ISSUE THREAD

**Issue by 963yms** [AIR-THU/DAIR-V2X#63]

**Comment by haibao-yu** [comment]
Certainly, please refer to the following links for more information:

- For the repository, visit: https://github.com/AIR-THU/DAIR-V2X-Seq
- For the detailed readme about the v2x-seq-spd dataset, visit: https://github.com/AIR-THU/DAIR-V2X-Seq/tree/main/dataset/v2x-seq-spd
