### ISSUE TITLE
请问dev-v2x-seq现在可以用了吗？

### ISSUE THREAD

**Issue by chensiweiTHU** [AIR-THU/DAIR-V2X#65]

**Comment by haibao-yu** [comment]
Certainly, please refer to the following links for more information:

- For the repository, visit: https://github.com/AIR-THU/DAIR-V2X-Seq
-  For the detailed readme about the v2x-seq-spd dataset, visit: https://github.com/AIR-THU/DAIR-V2X-Seq/tree/main/dataset/v2x-seq-spd
- For the detailed readme about the v2x-seq-tfd dataset, visit: https://github.com/AIR-THU/DAIR-V2X-Seq/tree/main/dataset/v2x-seq-tfd
