### ISSUE TITLE
Request access for DAIR-V2X

### ISSUE THREAD

**Issue by melihyazgan** [AIR-THU/DAIR-V2X#67]
Dear Researchers,

I hope this email finds you well. I am writing to ask about the availability of a specific dataset I am interested in using for my research project. After a thorough search, I discovered that the dataset is publicly available for direct website downloading within mainland China. However, since I am located outside mainland China, I understand I need to contact you to request access. The dataset I am referring to is DAIR-V2X.

From my initial assessment, it appears to be a valuable resource for my research. I believe it would significantly contribute to advancing my work in cooperative perception by using infrastructure sensors. I would be grateful if you could provide me access to the dataset. To facilitate this process, please let me know the preferred method of data transfer or any specific steps I need to follow. If any associated costs or fees or usage policies, licensing terms, or restrictions are associated with the dataset, kindly provide the relevant details so I can make appropriate arrangements. Thank you very much for considering my request. I am genuinely excited about the prospect of working with this dataset and believe it will significantly enhance the quality and impact of my research.
I look forward to hearing back from you. If you have any questions or require any additional information, please do not hesitate to let me know.

Best Regards,
Melih Yazgan

**Comment by haibao-yu** [comment]
Thank you for your interest in our dataset. Please note that, at present, the dataset is officially available for download and use exclusively within Mainland China.

To help researchers become acquainted with our data, we have provided a Google Drive link for direct download of an example dataset. 
 - DAIR-V2X-C-Example: [google_drive_link](https://drive.google.com/file/d/1y8bGwI63TEBkDEh2JU_gdV7uidthSnoe/view?usp=drive_link)
 - V2X-Seq-SPD-Example: [google_drive_link](https://drive.google.com/file/d/1gjOmGEBMcipvDzu2zOrO9ex_OscUZMYY/view?usp=drive_link)
 - V2X-Seq-TFD-Example: [google_drive_link](https://drive.google.com/file/d/1gjOmGEBMcipvDzu2zOrO9ex_OscUZMYY/view?usp=drive_link)

 If you wish to utilize our complete dataset, we encourage collaboration with researchers based in Mainland China.
