### ISSUE TITLE
dataset download problem

### ISSUE THREAD

**Issue by Yolan1013** [AIR-THU/DAIR-V2X#71]
Thank you for your excellent work!
But I met the problem when I try to download dataset form the official website. I have waited for several days, but the result is still the same. Can you help me with that?
![Screenshot from 2023-09-01 14-17-36](https://github.com/AIR-THU/DAIR-V2X/assets/34823398/0ca23d71-187e-4626-b9b4-ff27dd0c58ed)

**Comment by haibao-yu** [comment]
The downloading problem has been solved. Please try again.
