### ISSUE TITLE
multimodal fusion problem

### ISSUE THREAD

**Issue by wanghangege** [AIR-THU/DAIR-V2X#72]
Hello, can dairv2x-i perform multimodal fusion? The visual labels and LiDAR labels of this dataset are separate, and the projection parameters do not seem to combine the two well. Does this mean that this dataset cannot perform multimodal fusion?

**Comment by xduxiaohai** [comment]
I also discovered this problem. The labels of LiDAR seem to be inconsistent with those of Camera. So which label should I refer to when doing multi-modal fusion?
![image](https://github.com/AIR-THU/DAIR-V2X/assets/53559220/86538537-8bbd-4c9c-8b30-557100ebfd81)
Not only that, the label box is sometimes biased when projected onto the image
![image](https://github.com/AIR-THU/DAIR-V2X/assets/53559220/e4f1dd93-658c-481c-ac1e-3d1fb53f004b)
![image](https://github.com/AIR-THU/DAIR-V2X/assets/53559220/3019a704-4764-4f60-9483-cc5ca579a512)

**Comment by haibao-yu** [comment]
> Hello, can dairv2x-i perform multimodal fusion? The visual labels and LiDAR labels of this dataset are separate, and the projection parameters do not seem to combine the two well. Does this mean that this dataset cannot perform multimodal fusion?

Thanks for your question. You can convert the dataset into KITTI format as https://github.com/AIR-THU/DAIR-V2X/blob/main/docs/data_converter.md. Then you can use mmdetection3d to train multimodal model on this converted dataset.

**Comment by haibao-yu** [comment]
> I also discovered this problem. The labels of LiDAR seem to be inconsistent with those of Camera. So which label should I refer to when doing multi-modal fusion? ![image](https://private-user-images.githubusercontent.com/53559220/287729342-86538537-8bbd-4c9c-8b30-557100ebfd81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMjA0NjksIm5iZiI6MTcwNTEyMDE2OSwicGF0aCI6Ii81MzU1OTIyMC8yODc3MjkzNDItODY1Mzg1MzctOGJiZC00YzljLThiMzAtNTU3MTAwZWJmZDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDA0MjkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYTcxZWU3NjE0YWQxYzdlZTEwNWFiYjJmZTVmODI0MWE2ZGY4MzliM2FjNDI4NjUxMzNhOTg4NmUwZjg1MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FNDbjAVAM5rS6R-TfvkXvEmyt6AMTaWtim7P8ngtMVw) Not only that, the label box is sometimes biased when projected onto the image ![image](https://private-user-images.githubusercontent.com/53559220/287729776-e4f1dd93-658c-481c-ac1e-3d1fb53f004b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMjA0NjksIm5iZiI6MTcwNTEyMDE2OSwicGF0aCI6Ii81MzU1OTIyMC8yODc3Mjk3NzYtZTRmMWRkOTMtNjU4Yy00ODFjLWFjMWUtM2QxZmI1M2YwMDRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDA0MjkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMjI4MDkwNGFlMTA1OTM2YmIzNjU2ZjEwNDY2MTRkYzc1MGJiMTJkYjZhMGIyYTNiNWVkZTA3MTY5Y2RlOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.plwfnpS9xd4M0yVkq6BY73Qvu11VGDawOeOIhRUcP-Q) ![image](https://private-user-images.githubusercontent.com/53559220/287729781-3019a704-4764-4f60-9483-cc5ca579a512.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMjA0NjksIm5iZiI6MTcwNTEyMDE2OSwicGF0aCI6Ii81MzU1OTIyMC8yODc3Mjk3ODEtMzAxOWE3MDQtNDc2NC00ZjYwLTk0ODMtY2M1Y2E1NzlhNTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDA0MjkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMDVmMzJkMTYyY2E0ZDIxYjNlOTVjZjU3ZDNmMWE4Yzg3ZGQ2MjcwYjBmNDA5NzNlNjdmNzUxOTMxZTk4OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w2x5kc9ej7UtqsPkflU2nGHybCPFyurme4XIjSCB0fY)

Yes, there is no strict synchronization between the camera and LiDAR. Consequently, we supply two types of labels, each corresponding to either the camera or LiDAR data. For effective multimodal fusion detection, we recommend utilizing LiDAR as the primary sensor, with its corresponding label serving as the ground truth.
