### ISSUE TITLE
Dataset request -- V2X-Seq -- Outside Mainland China

### ISSUE THREAD

**Issue by DerejeCShenkut** [AIR-THU/DAIR-V2X#74]
Hi,

I have repeatedly sent an email to dair@air.tsinghua.edu.cn requesting a download link for research outside China. 
Can you please respond?

Thanks,

**Comment by haibao-yu** [comment]
Thank you for your interest in our dataset. Please note that, at present, the dataset is officially available for download and use exclusively within Mainland China.

To help researchers become acquainted with our data, we have provided a Google Drive link for direct download of an example dataset. 
 - DAIR-V2X-C-Example: [google_drive_link](https://drive.google.com/file/d/1y8bGwI63TEBkDEh2JU_gdV7uidthSnoe/view?usp=drive_link)
 - V2X-Seq-SPD-Example: [google_drive_link](https://drive.google.com/file/d/1gjOmGEBMcipvDzu2zOrO9ex_OscUZMYY/view?usp=drive_link)
 - V2X-Seq-TFD-Example: [google_drive_link](https://drive.google.com/file/d/1gjOmGEBMcipvDzu2zOrO9ex_OscUZMYY/view?usp=drive_link)

 If you wish to utilize our complete dataset, we encourage collaboration with researchers based in Mainland China.

**Comment by tugbakara** [comment]
Hi @haibao-yu , I also send the e-mail but noone turned back, how can I do to reach the full dataset?
