### ISSUE TITLE
BEV Map Segmentation

### ISSUE THREAD

**Issue by fjhzhixi** [AIR-THU/DAIR-V2X#93]
Thank you for your work on UniV2X. I am exploring the BEV map segments mentioned in your project and would appreciate guidance on where to find or how to generate the associated labels.

Could you please provide details or point me to the relevant documentation?

Thank you for your assistance.

**Comment by EchoQiHeng** [comment]
**I was also interested in the acquisition of HD maps!**

**Comment by haibao-yu** [comment]
Thanks for your interest. Our UniV2X includes online mapping task. The code will be released at at https://github.com/AIR-THU/UniV2X.
